//
//  ListTagsPresenter.swift
//  Scanner
//
//  Created by Zaizen Kaegyoshi on 4/17/19.
//  Copyright (c) 2019 zzzz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListTagsPresentationLogic
{
    func presentTags(response: ListTags.FetchTags.Response)
    func dismiss()
}

class ListTagsPresenter: ListTagsPresentationLogic
{
    weak var viewController: ListTagsDisplayLogic?
    
    // MARK: Do something
    
    func presentTags(response: ListTags.FetchTags.Response) {
        let tagModels = response.tags.map { (tag) -> ListTags.TagModel in
            return ListTags.TagModel.init(name: tag.0.name, color: UIColor.randomFlat(), selected: tag.1, depth: 0)
        }
        self.viewController?.displayTags(vm: ListTags.FetchTags.ViewModel.init(tags: tagModels, showingFolders: response.showingFolders))
    }
    func dismiss() {
        self.viewController?.dismiss()
    }
}
