//
//  ListTagsModels.swift
//  Scanner
//
//  Created by Zaizen Kaegyoshi on 4/17/19.
//  Copyright (c) 2019 zzzz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListTags
{
    // MARK: Use cases
    struct TagModel {
        var name: String
        var color: UIColor
        var selected: Bool
        var depth: Int
    }
    enum FetchTags
    {
        struct Request
        {
            
        }
        struct Response
        {
            var tags: [(Tag, Bool)]
            var showingFolders: Bool
             // tag ids
        }
        struct ViewModel
        {
            var tags: [TagModel]
            var showingFolders: Bool
        }
    }
    enum SelectTags
    {
        struct Request
        {
            var selectedTags: [TagModel]
        }
        struct Response
        {
            
        }
        struct ViewModel
        {
            
        }
    }
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
}
