//
//  SettingsInteractor.swift
//  Scanner
//
//  Created by Zaizen Kaegyoshi on 5/1/19.
//  Copyright (c) 2019 zzzz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift


protocol SettingsBusinessLogic
{
    func deleteAll()
}

protocol SettingsDataStore
{
    //var name: String { get set }
}

class SettingsInteractor: SettingsBusinessLogic, SettingsDataStore
{
    var presenter: SettingsPresentationLogic?
    var worker: SettingsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func deleteAll() {
        let realm = try! Realm()
        try! realm.write {
            realm.deleteAll()
        }
        
        TestGenerator.addTags()
        TestGenerator.addChildTags()
        
        
    }
}
