//
//  ListFilesPresenter.swift
//  Scanner
//
//  Created by Zaizen Kaegyoshi on 4/8/19.
//  Copyright (c) 2019 zzzz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListFilesPresentationLogic
{
  func presentSomething(response: ListFiles.Something.Response)
}

class ListFilesPresenter: ListFilesPresentationLogic
{
  weak var viewController: ListFilesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ListFiles.Something.Response)
  {
    let viewModel = ListFiles.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
