//
//  ListFilesRouter.swift
//  Scanner
//
//  Created by Zaizen Kaegyoshi on 4/8/19.
//  Copyright (c) 2019 zzzz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListFilesRoutingLogic
{
    func routeToShowFile(segue: UIStoryboardSegue?)
    func routeToShowTags()
}

protocol ListFilesDataPassing
{
    var dataStore: ListFilesDataStore? { get }
}

class ListFilesRouter: NSObject, ListFilesRoutingLogic, ListFilesDataPassing
{
    weak var viewController: ListFilesViewController?
    var dataStore: ListFilesDataStore?
    
    // MARK: Routing
    func routeToShowFile(segue: UIStoryboardSegue?) {
        
        if let segue = segue {
            let destinationVC = segue.destination as! ShowFileViewController
//            destinationVC.modalTransitionStyle = .crossDissolve
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowFile(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ShowFileViewController") as! ShowFileViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowFile(source: dataStore!, destination: &destinationDS)
            navigateToShowFile(source: viewController!, destination: destinationVC)
        }
    }
    func navigateToShowFile(source: ListFilesViewController, destination: ShowFileViewController)
    {
//        source.present
//        source.show(destination, sender: nil)
        if let indexPath = viewController?.allTableView.indexPathForSelectedRow {
            if indexPath.row >= 2 {
                source.present(destination, animated: true, completion: nil)
            }
            
        } else {
            source.present(destination, animated: true, completion: nil)
        }
        
    }
    
//    MARK: Passing data
    
    func passDataToShowFile(source: ListFilesDataStore, destination: inout ShowFileDataStore)
    {
        
        if let indexPath = viewController?.allTableView.indexPathForSelectedRow {
            if indexPath.row >= 2 {
                destination.file = viewController?.files[indexPath.row - 2]
            }
            
        } else {
            
            destination.file = nil
        }
    }
    func routeToShowTags() {
        
        
        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "ListTags") as! ListTagsViewController

        
        
        var destinationDS = destinationVC.router!.dataStore!
        passDataToShowTags(source: dataStore!, destination: &destinationDS)
        navigateToShowTags(source: viewController!, destination: destinationVC)
        
    }
    func navigateToShowTags(source: ListFilesViewController, destination: ListTagsViewController)
    {
        //        source.present
        //        source.show(destination, sender: nil)
        destination.modalPresentationStyle = .overCurrentContext
        destination.modalTransitionStyle = .crossDissolve
//        self.viewController!.present(destination, animated: true, completion: nil)
        source.present(destination, animated: true, completion: nil)
    }
    
    //    MARK: Passing data
    
    func passDataToShowTags(source: ListFilesDataStore, destination: inout ListTagsDataStore)
    {
        destination.showingFolders = false
        destination.tags = TagManager.sharedInstance.fetchTags()
//        if let indexPath = viewController?.allTableView.indexPathForSelectedRow {
//            destination.file = viewController?.files[indexPath.row - 2]
//        } else {
//            destination.file = nil
//        }
    }
    
    
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: ListFilesViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: ListFilesDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
