//
//  AddTagRouter.swift
//  Scanner
//
//  Created by Zaizen Kaegyoshi on 5/1/19.
//  Copyright (c) 2019 zzzz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddTagRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    func dismiss()
}

protocol AddTagDataPassing
{
    var dataStore: AddTagDataStore? { get }
}

class AddTagRouter: NSObject, AddTagRoutingLogic, AddTagDataPassing
{
    weak var viewController: AddTagViewController?
    var dataStore: AddTagDataStore?
    
    // MARK: Routing
    
    func dismiss() {
        let destinationVC = self.viewController?.presentingViewController
        if let vc = (destinationVC as? ListTagsViewController) {
//            var destinationDS = vc.router!.dataStore!
            vc.disableTouchToDismiss = false
            
            navigateBack(source: self.viewController!)
        } else {
            
            navigateBack(source: self.viewController!)
        }
    }
    func navigateBack(source: AddTagViewController ) {
        source.dismiss(animated: true, completion: nil)
    }
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: AddTagViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: AddTagDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
