//
//  AddTagInteractor.swift
//  Scanner
//
//  Created by Zaizen Kaegyoshi on 5/1/19.
//  Copyright (c) 2019 zzzz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddTagBusinessLogic
{
    func addTag(request: AddTag.AddTag.Request)
}

protocol AddTagDataStore
{
    //var name: String { get set }
}

class AddTagInteractor: AddTagBusinessLogic, AddTagDataStore
{
    var presenter: AddTagPresentationLogic?
    var worker: AddTagWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func addTag(request: AddTag.AddTag.Request) {
        let tag = Tag(name: request.name)
        tag.write(dataStore: TagManager.sharedInstance)
        self.presenter?.dismiss()
    }
    
}
