//
//  AddTagPresenter.swift
//  Scanner
//
//  Created by Zaizen Kaegyoshi on 5/1/19.
//  Copyright (c) 2019 zzzz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddTagPresentationLogic
{
    func dismiss()
}

class AddTagPresenter: AddTagPresentationLogic
{
    weak var viewController: AddTagDisplayLogic?
    
    // MARK: Do something
    func dismiss() {
        self.viewController?.dismiss()
    }
    
}
