//
//  ShowFilePresenter.swift
//  Scanner
//
//  Created by Zaizen Kaegyoshi on 4/11/19.
//  Copyright (c) 2019 zzzz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowFilePresentationLogic
{
    func presentNewFile()
    func presentFile(response: ShowFile.FetchFile.Response)
    func dismiss()
}

class ShowFilePresenter: ShowFilePresentationLogic
{
    weak var viewController: ShowFileDisplayLogic?
    
    // MARK: Do something
    
    
    func presentNewFile() {
        self.viewController?.displayNewFile()
    }
    func presentFile(response: ShowFile.FetchFile.Response) {
        
    }
    func dismiss() {
        viewController?.dismiss(animated: true, completion: nil)
    }
}
