//
//  ShowFileRouter.swift
//  Scanner
//
//  Created by Zaizen Kaegyoshi on 4/11/19.
//  Copyright (c) 2019 zzzz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowFileRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToShowTags(withFolder: Bool)
}

protocol ShowFileDataPassing
{
    var dataStore: ShowFileDataStore? { get }
}

class ShowFileRouter: NSObject, ShowFileRoutingLogic, ShowFileDataPassing
{
    weak var viewController: ShowFileViewController?
    var dataStore: ShowFileDataStore?
    
    // MARK: Routing
    
    func routeToShowTags(withFolder: Bool) {
        
        
        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "ListTags") as! ListTagsViewController
        
        
        
        var destinationDS = destinationVC.router!.dataStore!
        if withFolder {
            passFoldersToShowTags(source: dataStore!, destination: &destinationDS)
        } else {
            passTagsToShowTags(source: dataStore!, destination: &destinationDS)
        }
        
        
        navigateToShowTags(source: viewController!, destination: destinationVC)
        
    }
    func navigateToShowTags(source: ShowFileViewController, destination: ListTagsViewController)
    {
        //        source.present
        //        source.show(destination, sender: nil)
        destination.modalPresentationStyle = .overCurrentContext
        destination.modalTransitionStyle = .crossDissolve
        //        self.viewController!.present(destination, animated: true, completion: nil)
        source.present(destination, animated: true, completion: nil)
    }
    
    //    MARK: Passing data
    
    func passTagsToShowTags(source: ShowFileDataStore, destination: inout ListTagsDataStore)
    {
        destination.showingFolders = false
        destination.tags = TagManager.sharedInstance.fetchTags()
        destination.file = source.file
        
    }
    func passFoldersToShowTags(source: ShowFileDataStore, destination: inout ListTagsDataStore)
    {
        destination.showingFolders = true
        destination.tags = TagManager.sharedInstance.fetchTopFolders()
        destination.file = source.file
        
    }
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: ShowFileViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: ShowFileDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
