//
//  ShowFileModels.swift
//  Scanner
//
//  Created by Zaizen Kaegyoshi on 4/11/19.
//  Copyright (c) 2019 zzzz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation

enum ShowFile
{
    // MARK: Use cases
    
    struct FileModel {
        var name: String
        var date: String
        var pageImages: [UIImage]
        var location: CLLocationCoordinate2D?
        var fullAddress: String
        var tags: [ListFiles.TagModel]
        var notes: String
        var folder: String
    }
    
    enum FetchFile {
        struct Request
        {
        }
        struct Response
        {
            var file: File
        }
        struct ViewModel
        {
            var file: FileModel
        }
    }
    enum SaveFile
    {
        struct Request
        {
            var file: FileModel
            var pageImages: [UIImage]
        }
        struct Response
        {
            
        }
        struct ViewModel
        {
            
        }
    }
    
}
