//
//  ShowFileInteractor.swift
//  Scanner
//
//  Created by Zaizen Kaegyoshi on 4/11/19.
//  Copyright (c) 2019 zzzz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowFileBusinessLogic
{
    func saveFile(request: ShowFile.SaveFile.Request)
    func fetchFile()
}

protocol ShowFileDataStore
{
    var file: File? { get set }
}

class ShowFileInteractor: ShowFileBusinessLogic, ShowFileDataStore
{
    var presenter: ShowFilePresentationLogic?
    var worker: ShowFileWorker?
//    var fileWorker : FileWorker!
    var fpManager = FilePageManager.sharedInstance
    var file: File?
    
    
    // MARK: Do something
    func fetchFile() {
        if let f = self.file {
            self.presenter?.presentFile(response: ShowFile.FetchFile.Response.init(file: f))
        } else {
            self.file = FileWorker.newFile()
            self.presenter?.presentNewFile()
        }
    }
    func saveFile(request: ShowFile.SaveFile.Request) {
        let images = request.pageImages
        let fileWorker = FileWorker()
        self.file = fileWorker.addPagesTo(file: self.file!, pageImages: images)
        self.file?.write(dataStore: fpManager)
        self.file = nil
        self.presenter?.dismiss()
        
    }
    
    
//    func doSomething(request: ShowFile.Something.Request)
//    {
//        worker = ShowFileWorker()
//        worker?.doSomeWork()
//
//        let response = ShowFile.Something.Response()
//        presenter?.presentSomething(response: response)
//    }
}
