//
//  ShowFileModels.swift
//  Scanner
//
//  Created by Zaizen Kaegyoshi on 4/11/19.
//  Copyright (c) 2019 zzzz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowFile
{
    // MARK: Use cases
    
    enum FetchFile {
        struct Request
        {
        }
        struct Response
        {
            var file: File
        }
        struct ViewModel
        {
        }
    }
    
    
}
